# Generated by Django 4.2.6 on 2023-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript')], max_length=20)),
            ],
        ),
    ]
