# Generated by Django 4.2.6 on 2023-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exerciseforum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
