# Generated by Django 4.2.6 on 2023-12-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exerciseforum', '0002_proglanguage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
